### ISSUE TITLE
Yarn GPG key expiry prevents running apt

### ISSUE THREAD

**Issue by Apreche** [devcontainers/images#370]
Create a very simple `Dockerfile` like this:

```Dockerfile
ARG VARIANT=3.8
FROM mcr.microsoft.com/devcontainers/python:0-${VARIANT}
RUN apt-get update
```
If you try to build this with `docker build .` you will get the error:
```
user@localhost $ docker build .
[+] Building 1.7s (5/5) FINISHED                                                                                                     
 => [internal] load build definition from Dockerfile                                                                            0.0s
 => => transferring dockerfile: 135B                                                                                            0.0s
 => [internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/python:0-3.8                                                   0.3s
 => CACHED [1/2] FROM mcr.microsoft.com/devcontainers/python:0-3.8@sha256:619df220ed3f7c91e96785e8794c1b7ac7af8c27e50be16c8f08  0.0s
 => ERROR [2/2] RUN apt-get update                                                                                              1.4s
------                                                                                                                               
 > [2/2] RUN apt-get update:                                                                                                         
#5 0.190 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]                                                              
#5 0.198 Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                                                              
#5 0.227 Get:3 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]                                           
#5 0.242 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]                                                     
#5 0.246 Err:2 https://dl.yarnpkg.com/debian stable InRelease
#5 0.246   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#5 0.330 Get:5 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
#5 0.536 Get:6 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [211 kB]
#5 0.558 Get:7 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
#5 1.142 Reading package lists...
#5 1.375 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#5 1.375 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
------
executor failed running [/bin/sh -c apt-get update]: exit code: 100
```
An issue for this error can be seen here:
https://github.com/yarnpkg/yarn/issues/7866

Attempts to use any of the solutions such as:
```bash
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - 
```
```bash
sudo apt-key adv --refresh-keys --keyserver keyserver.ubuntu.com
```
or
```bash
wget -qO - https://raw.githubusercontent.com/yarnpkg/releases/gh-pages/debian/pubkey.gpg | sudo apt-key add -
```
prior to the `apt-get update` do not fix the problem.

You can see here:
https://github.com/yarnpkg/releases/blob/gh-pages/debian/pubkey.gpg
The pubkey was updated 13 hours ago as of the time of this posting. Even that brand new key does not seem to work.

I consider this issue to be quite urgent as it completely prevents me from building my VSCode Python dev environment. I can't get any work done unless I come up with a new environment using a different docker base image.

**Comment by rafaelfranca** [comment]
Same thing is happening in the Ruby image.

**Comment by bobvandevijver** [comment]
Just use `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`, which fixed it here.

**Comment by sreid99** [comment]
> Same thing is happening in the Ruby image.

Same - Ruby 3.1-bullseye

**Comment by jvdavim** [comment]
> Just use `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`, which fixed it here.

Debian from bullseye has deprecated `apt-key`.

Ref.: https://manpages.debian.org/bullseye/apt/apt-key.8.en.html

**Comment by Apreche** [comment]
> Just use `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`, which fixed it here.

As I explained in the original post, this did **not** fix the problem for me.

```bash
user@localhost $ cat Dockerfile 
ARG VARIANT=3.11
FROM mcr.microsoft.com/devcontainers/python:0-${VARIANT}
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN apt-get update
user@localhost $ docker build .
[+] Building 1.8s (6/6) FINISHED                                                                                                     
 => [internal] load build definition from Dockerfile                                                                            0.0s
 => => transferring dockerfile: 37B                                                                                             0.0s
 => [internal] load .dockerignore                                                                                               0.0s
 => => transferring context: 2B                                                                                                 0.0s
 => [internal] load metadata for mcr.microsoft.com/devcontainers/python:0-3.11                                                  0.1s
 => [1/3] FROM mcr.microsoft.com/devcontainers/python:0-3.11@sha256:1aaa54bf036f6d49ec3afe4688eae0c2b75f7f0e4e7526af03753a1845  0.0s
 => CACHED [2/3] RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -                                     0.0s
 => ERROR [3/3] RUN apt-get update                                                                                              1.6s
------                                                                                                                               
 > [3/3] RUN apt-get update:                                                                                                         
#6 0.180 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]                                                              
#6 0.190 Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]                                                              
#6 0.218 Get:3 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]                                           
#6 0.239 Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]                                                     
#6 0.242 Err:2 https://dl.yarnpkg.com/debian stable InRelease
#6 0.242   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#6 0.342 Get:5 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
#6 0.735 Get:6 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [212 kB]
#6 0.739 Get:7 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
#6 1.311 Reading package lists...
#6 1.540 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#6 1.540 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
------
executor failed running [/bin/sh -c apt-get update]: exit code: 100
srubin ~/Projects/msdockertest $ 
```

**Comment by Chuxel** [comment]
Yarn's key must have expired, so the images need to be rev'd to get the latest key.  Tactically, you can remove the yarn source to work around this. e.g., in a Dockerfile

```
RUN rm -f /etc/apt/sources.list.d/yarn.list
```

**Comment by mathieujobin** [comment]
I tried putting the key in `/usr/share` as suggested above.
`curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor > /usr/share/keyrings/yarn-archive-keyring.gpg`
and also `cp /usr/share/keyrings/yarn-archive-keyring.gpg /etc/apt/trusted.gpg.d/`

but `apt update` still complains, on Ubuntu 22.04 LTS

**Comment by Chuxel** [comment]
> I tried putting the key in `/usr/share` as suggested above. `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor > /usr/share/keyrings/yarn-archive-keyring.gpg` and also `cp /usr/share/keyrings/yarn-archive-keyring.gpg /etc/apt/trusted.gpg.d/`
> 
> but `apt update` still complains, on Ubuntu 22.04 LTS

What image are you using? The location of this file can vary - this is just where the ones in devcontainers/images place it.

```bash
❯ docker run -it --rm mcr.microsoft.com/devcontainers/ruby bash
root ➜ / $ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor > /usr/share/keyrings/yarn-archive-keyring.gpg
root ➜ / $ apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]
Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Get:6 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
Get:7 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
Get:8 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [216 kB]
Get:9 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8661 kB in 2s (3517 kB/s)
Reading package lists... Done
root ➜ / $
```

**Comment by samruddhikhandale** [comment]
The images release is still in progress, however, new images for "Python" & "Ruby" are published. The issue should be fixed for these two images.

@Apreche / @sreid99 Can you rebuild and try again?

**Comment by Apreche** [comment]
> The images release is still in progress, however, new images for "Python" & "Ruby" are published. The issue should be fixed for these two images.
> 
> @Apreche / @sreid99 Can you rebuild and try again?

I have confirmed it is now working. Thank you very much.

**Comment by samruddhikhandale** [comment]
All images are published. Closing as completed 🚀

**Comment by adalbertobrant** [comment]
Hi I tried to  work with the solution proposed here, but the error persist.
So I did this:
1. sudo apt-key list yarn
![image](https://user-images.githubusercontent.com/6125981/214509551-645db48d-c8e3-46a1-bfbf-831ddb7d9bb8.png)

As you can see I still have the keys, following the instructions on this page , but It was not in the correct place for Ubuntu 22.04 LTS , because I am not using docker here.

2. sudo apt-key del ( last 8 chars from the hex key)
![image](https://user-images.githubusercontent.com/6125981/214510065-5dde3355-faa2-4366-8bbe-71a15adb9885.png)

3. Acording to `man apt-key `in the section DEPRECREATION , there is a new dir that I should to use , for my Ubuntu 22.04 LTS it is in 
`/etc/apt/trusted.gpg.d`
![image](https://user-images.githubusercontent.com/6125981/214510418-d3eae1d0-4e6c-46ab-b63c-a1d18650bc0f.png)

4. After that I use the command `sudo su`, to elevate rights , and use the command explained by Mr. @Chuxel  as it was, with an alteration in the key placement to be compatible with a not image, yeap I use sudo , even I already with root, sorry about that.
`sudo curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --dearmor > /etc/apt/trusted.gpg.d/yarn-archive-keyring.gpg
`
5. Following that, just did `sudo apt update ` with su in root and also without ,and it worked just fine.
![image](https://user-images.githubusercontent.com/6125981/214511513-9fd952fb-d2f9-4fcb-b6cc-f2d18cd19a8e.png)
![image](https://user-images.githubusercontent.com/6125981/214511600-6432959a-2b62-49bd-af2e-cf0b86f006d4.png)

I received help from here also -> [https://linuxuniverse.com.br/linux/trusted](urhttps://linuxuniverse.com.br/linux/trusted)

**Comment by Chuxel** [comment]
If you have any Dev Container images cached locally, you may need to execute a `docker pull` command to pull down the latest image. 

e.g., `docker pull mcr.microsoft.com/devcontainers/python:0-3.11`

**Comment by Apreche** [comment]
Thanks again for the quick fix on this, I would just like to discuss what strategy there is for this problem going forward.

Is there some sort of automated system in place to prevent this from happening again? I can imagine something that detects if the keys change, or waits for the expiration date, and then automatically makes a pull request. Sort of like dependabot.

Is there something that can be done in yarn or apt? It was good that they were diligent and put out a new key pretty much as soon as the old one expired. But is there some way they could have had a brief overlapping period with two valid keys to allow a smoother transition?

Any sort of defense mechanism to ensure that images can't be broken by the actions of a third party would be most welcome.

**Comment by stevennyman** [comment]
I'm using a `Dockerfile` with the following contents to create a Codespace and I am still having a similar issue with the 2.2.3 universal image:

```Dockerfile
FROM mcr.microsoft.com/devcontainers/universal:2.2.3
RUN apt-get update
```

Error
```
2023-01-25 16:55:40.946Z: #5 1.317 Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#5 1.331 Get:2 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease [10.5 kB]
#5 1.385 Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]2023-01-25 16:55:40.959Z: 
#5 1.398 Get:4 https://repo.anaconda.com/pkgs/misc/debrepo/conda stable InRelease [3171 B]
#5 1.413 Err:2 https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease
#5 1.413   At least one invalid signature was encountered.
2023-01-25 16:55:41.055Z: #5 1.492 Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
#5 1.492   At least one invalid signature was encountered.
#5 1.524 Get:5 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
2023-01-25 16:55:41.206Z: #5 1.536 Err:3 https://dl.yarnpkg.com/debian stable InRelease
#5 1.536   At least one invalid signature was encountered.
#5 1.574 Err:4 https://repo.anaconda.com/pkgs/misc/debrepo/conda stable InRelease
#5 1.574   At least one invalid signature was encountered.
2023-01-25 16:55:41.485Z: #5 1.953 Err:5 http://archive.ubuntu.com/ubuntu focal InRelease
#5 1.953   At least one invalid signature was encountered.
2023-01-25 16:55:41.609Z: #5 1.971 Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#5 1.997 Get:6 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease [24.4 kB]
#5 2.053 Err:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease
#5 2.053   At least one invalid signature was encountered.2023-01-25 16:55:41.612Z: 
#5 2.077 Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
2023-01-25 16:55:41.715Z: #5 2.099 Err:6 https://packagecloud.io/github/git-lfs/ubuntu focal InRelease
#5 2.099   At least one invalid signature was encountered.
#5 2.156 Err:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease
#5 2.156   At least one invalid signature was encountered.
#5 2.182 Reading package lists...2023-01-25 16:55:41.845Z: 
#5 2.202 W: GPG error: https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'https://packages.microsoft.com/repos/microsoft-ubuntu-focal-prod focal InRelease' is not signed.
#5 2.202 W: GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'http://security.ubuntu.com/ubuntu focal-security InRelease' is not signed.
#5 2.202 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
#5 2.202 W: GPG error: https://repo.anaconda.com/pkgs/misc/debrepo/conda stable InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'https://repo.anaconda.com/pkgs/misc/debrepo/conda stable InRelease' is not signed.
#5 2.202 W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
#5 2.202 W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
2023-01-25 16:55:41.854Z: #5 2.202 E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
2023-01-25 16:55:41.862Z: #5 2.202 W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu focal InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu focal InRelease' is not signed.
#5 2.202 W: GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
#5 ERROR: executor failed running [/bin/sh -c apt-get update]: exit code: 100
------
 > [dev_container_auto_added_stage_label 2/2] RUN apt-get update:
#5 2.202 W: GPG error: https://repo.anaconda.com/pkgs/misc/debrepo/conda stable InRelease: At least one invalid signature was encountered.
2023-01-25 16:55:41.864Z: #5 2.202 E: The repository 'https://repo.anaconda.com/pkgs/misc/debrepo/conda stable InRelease' is not signed.
#5 2.202 W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
#5 2.202 W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
#5 2.202 W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu focal InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu focal InRelease' is not signed.
#5 2.202 W: GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
#5 2.202 E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
```

**Comment by Chuxel** [comment]
> Thanks again for the quick fix on this, I would just like to discuss what strategy there is for this problem going forward.
> 
> Is there some sort of automated system in place to prevent this from happening again? I can imagine something that detects if the keys change, or waits for the expiration date, and then automatically makes a pull request. Sort of like dependabot.
> 
> Is there something that can be done in yarn or apt? It was good that they were diligent and put out a new key pretty much as soon as the old one expired. But is there some way they could have had a brief overlapping period with two valid keys to allow a smoother transition?
> 
> Any sort of defense mechanism to ensure that images can't be broken by the actions of a third party would be most welcome.

We strongly encourage [pre-building your images](https://containers.dev/implementors/reference/#prebuilding) to avoid these kinds of issues rather than installing something on the fly. For awareness, the problem seen here also happened for local Linux users, caused by the up-stream source (yarn itself). If you are using Codespaces, doing Codespace pre-builds can help as well.

**Comment by rudi1602** [comment]
> All images are published. Closing as completed 🚀

What do you mean by 'all images'? All DevContainer images? What about **mcr.microsoft.com/devcontainers/java:1-21-bullseye**?
